OUTPUT_DIR: "exp_common"
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1333
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RATIO_ON: True
  WEIGHT: "data/R-101.pkl"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    PRE_NMS_TOP_N_TRAIN: 1200
    PRE_NMS_TOP_N_TEST: 1200
    FPN_POST_NMS_TOP_N_TRAIN: 1200
    FPN_POST_NMS_TOP_N_TEST: 600
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
    DETECTIONS_PER_IMG: 2000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNRatioPredictor"
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("Your own dataset",)
  TEST: ("Your own dataset",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0075
  WEIGHT_DECAY: 0.0001
  STEPS: (38000, 46000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 6
  CHECKPOINT_START_STEP: 30000
TEST:
  IMS_PER_BATCH: 12
