OUTPUT_DIR: "exp_dota/dota_proj_ms/exer4_ML_ADP_init2_aug_weight01_lr002"
#"exp_dota/dota_proj_exer2_aspp_init2_aug_weight01_lr2_adp"
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1333
  RANDOM_ROTATE_ON: True # (0, 90, 180, or 270)
  BRIGHTNESS: 0.
  CONTRAST: 0.
  SATURATION: 0.
  HUE: 0.
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  #RATIO_ON: True
  PROJ_ON: True
  PROJ_ADAPTIVE_WEIGHT: False #True
  MORPH_LEARNER: True
  MORPH_LEARNER_TYPE: 'ASPP' #'LKPP'
  WEIGHT: 'models/R-101.pkl' #e2e_faster_rcnn_R_101_FPN_1x.pth' #"data/R-101.pkl"
  WEIGHT_RESUME: False #True 
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    PRE_NMS_TOP_N_TRAIN: 1200
    PRE_NMS_TOP_N_TEST: 1200
    FPN_POST_NMS_TOP_N_TRAIN: 1200
    FPN_POST_NMS_TOP_N_TEST: 600
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
    DETECTIONS_PER_IMG: 2000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNProjPredictor" #"FPNRatioPredictor"
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("dota_trainval_cut",) #("dota_train",)
  TEST:  ("dota_trainval_cut",) #("dota_test_cut",) #("dota_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02 #0.0075
  WEIGHT_DECAY: 0.0001
  STEPS: (38000,46000,54000)
  MAX_ITER: 62000
  IMS_PER_BATCH: 8 # 4A
  CHECKPOINT_START_STEP: 30000
TEST:
  IMS_PER_BATCH: 8
  #BBOX_AUG:
    #ENABLED: True
    #H_FLIP: True
